name: mlg-project
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py311h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - certifi=2025.10.5=py311haa95532_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - cuda-cccl=13.0.85=h5221881_1
  - cuda-cccl_win-64=13.0.85=hc667259_1
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.0.85=h17533db_0
  - cuda-opencl-dev=13.0.85=hde976d8_0
  - cuda-profiler-api=13.0.85=h5221881_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.0=3
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=py311haa95532_0
  - freetype=2.13.3=h0620614_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py311h827c3e9_0
  - idna=3.11=py311haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jinja2=3.1.6=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.4.0.35=h86a452a_1
  - libcurand-dev=10.4.0.35=hde976d8_1
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.50=h46444df_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py311haa95532_0
  - networkx=3.5=py311haa95532_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - pillow=11.1.0=py311h096bfcc_0
  - pip=25.2=pyhc872135_1
  - pycparser=2.23=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - pytorch=2.1.2=py3.11_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h827c3e9_0
  - requests=2.32.5=py311haa95532_1
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - sympy=1.14.0=py311haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - typing_extensions=4.15.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - asttokens==3.0.0
      - attrs==25.4.0
      - colorama==0.4.6
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - executing==2.2.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ipykernel==7.1.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - matplotlib-inline==0.2.1
      - multidict==6.7.0
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - packaging==25.0
      - parso==0.8.5
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.1.3
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - scipy==1.16.3
      - six==1.17.0
      - stack-data==0.6.3
      - torch-cluster==1.6.3+pt21cu121
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt21cu121
      - torch-sparse==0.6.18+pt21cu121
      - torch-spline-conv==1.2.2+pt21cu121
      - torchaudio==2.1.2
      - torchvision==0.16.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - wcwidth==0.2.14
      - xxhash==3.6.0
      - yarl==1.22.0
