name: scraper
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.7.15=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.17=h35632f6_0
  - pip=25.2=pyhc872135_0
  - python=3.12.11=h716150d_0
  - setuptools=78.1.1=py312haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - attrs==25.3.0
      - certifi==2025.8.3
      - cffi==1.17.1
      - h11==0.16.0
      - idna==3.10
      - numpy==2.3.2
      - outcome==1.3.0.post0
      - pandas==2.3.2
      - pycparser==2.22
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - selenium==4.35.0
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - trio==0.30.0
      - trio-websocket==0.12.2
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - websocket-client==1.8.0
      - wsproto==1.2.0
